### ISSUE TITLE
Panicked when starting the pool server

### ISSUE THREAD

**Issue by rlinxy** [HarukaMa/aleo-pool-server#15]
Used to start successfully, no idea what I did, it cant be started now.
Please take a look, thanks.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError                                                         { io_error: Error { kind: UnexpectedEof, message: "failed to fill whole buffer"                                                         } }', src/accounting.rs:74:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/                                                        panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src                                                        /panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src                                                        /result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src                                                        /result.rs:1107:23
   4: aleo_pool_server::accounting::PPLNS::load
             at ./src/accounting.rs:74:9
   5: aleo_pool_server::accounting::Accounting::init
             at ./src/accounting.rs:145:47
   6: aleo_pool_server::main::{{closure}}
             at ./src/main.rs:126:22
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Futur                                                        e>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src                                                        /future/mod.rs:91:19
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/park.rs:283:63
   9: tokio::runtime::coop::with_budget
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/coop.rs:102:5
  10: tokio::runtime::coop::budget
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/coop.rs:68:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/park.rs:283:31
  12: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/context.rs:295:13
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  14: tokio::runtime::runtime::Runtime::block_on
             at /home/ray/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-                                                        1.23.0/src/runtime/runtime.rs:284:45
  15: aleo_pool_server::main
             at ./src/main.rs:146:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src                                                        /ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose bac                                                        ktrace.`

**Comment by HarukaMa** [comment]
Looks like the file `~/.aleo_pool_testnet3_2/state` is corrupted. This file stores the PPLNS state; you can safely discard it if you are using it as a private pool (i.e. not recording contributions for each address).

**Comment by rlinxy** [comment]
Thanks, solved
