### ISSUE TITLE
aleo-pool-server An error occurs when running.

### ISSUE THREAD

**Issue by moonlightpark** [HarukaMa/aleo-pool-server#16]
2024-01-26T20:27:53.441343Z  INFO aleo_pool_server::validator_peer: Connecting to operator...
2024-01-26T20:27:58.443197Z ERROR aleo_pool_server::validator_peer: Failed to connect to operator: Timed out

I am curious why the operator: Timed out error occurs.

**Comment by HarukaMa** [comment]
this repo hasn't been updated for almost a year already so it can't be directly used right now. not sure if I will update it soon. probably after mainnet.

**Comment by moonlightpark** [comment]
> this repo hasn't been updated for almost a year already so it can't be directly used right now. not sure if I will update it soon. probably after mainnet.

Thank you for responding even in the midst of your busy schedule.
