### ISSUE TITLE
No database host defined

### ISSUE THREAD

**Issue by antiwinter** [HarukaMa/aleo-pool-server#8]
Hi, thank you for creating such a useful repo for us to study aleo.
I am debugging the **aleo-prover**, but somehow got banned by the online pool sever (pool.hamp.app:4200).

So I am trying to start this pool server by myself, but got the error below:

```
    Finished release [optimized + debuginfo] target(s) in 1.16s
     Running `target/release/aleo-pool-server --operator '127.0.0.1:3032' --port 8888 --api-port 9999`
thread 'main' panicked at 'No database host defined', src/db.rs:17:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I start the operator by myself with the cmd below:
```
target/release/snarkos --operator aleo1cev9umxxxxxxx......xxxx --trial
```

BTW. What exact port number should I use for those ports in the aleo-pool-server command line?

**Comment by HarukaMa** [comment]
pool.hamp.app was having some issues around a snarkVM bug and I've mitigated it now.

The pool server currently requires a database but I'm trying to make it optional. If you want to actually use a database, you should use environment variables or `.env` file. See src/db.rs for the names of the env variables. 

I should document it but was busy implementing stratum protocol.

**Comment by HarukaMa** [comment]
Are they on the same version of the pool server? Database was a new feature (several days ago).

**Comment by HarukaMa** [comment]
Just pushed 0000052 and now you can use `cargo build --release --no-default-features` to turn off database features.
