### ISSUE TITLE
于节点通信报InvalidData

### ISSUE THREAD

**Issue by zhaocaipeng** [HarukaMa/aleo-pool-server#9]
snarkos 使用的HarukaMa最新版（使用官方最新的也是这个错）
aleo-pool-server 使用的最新版

Failed to read the message: Custom { kind: InvalidData, error: LengthDelimitedCodecError }
![image](https://user-images.githubusercontent.com/5387430/180371133-4505ea3f-53d6-440a-b3cd-5386787bda62.png)

**Comment by HarukaMa** [comment]
确保连接的是 operator p2p 端口（4132）

**Comment by HarukaMa** [comment]
reopen if there are still issues.
